spring.application.name=junior-sidekick

agent.name="Sidekick"
agent.state-directory=./data/state
agent.working-directory=./data/workspace

#
# Secrets to provide
#
adapters.slack.bot.token=
adapters.slack.bot.signing-secret=

adapters.open-router.api-key=
